### ISSUE TITLE
`user_id` seems to be case sensitive

### ISSUE THREAD

**Issue by disconn3ct** [isabellaalstrom/lovelace-grocy-chores-card#168]
Looking at Home Assistant under `config/person`, the usernames are lower case but the 'name' is capitalized. Putting those lower-case usernames into the card configuration doesn't work. With the `current` filter, it shows no events. Changing it from `username` to `Username` fixes it.

Full card:
``` yaml
type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
  - sensor.grocy_tasks
title: Upcoming Chores
show_quantity: 5
show_assigned: true
show_days: 2
show_overflow: true
show_chores_without_due: true
show_tasks_without_due: true
user_id:
  Username: 2
  Username2: 3
show_divider: true
use_icons: true
use_long_date: true
due_in_days_threshold: 5
use_24_hours: true
hide_text_with_no_data: true
show_description: true
```
