### ISSUE TITLE
Cannot see any card

### ISSUE THREAD

**Issue by apmillen** [isabellaalstrom/lovelace-grocy-chores-card#19]
I have configure the Grocy intergration and can see 3 chores from Grocy in sensor.grocy_chores.

I have installed card-tools (v2.3) and Lovelace Grocy Chores Card (v0.1.3)

In my ui-lovelace.yaml:
```
resources:
  - url: /community_plugin/lovelace-grocy-chores-card/grocy-chores-card.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module

views:
  - title: Chores
    cards:
      - type: custom:grocy-chores-card
        entity: sensor.grocy_chores
```

Nothing shows up with this config.

Am I doing something wrong?
