### ISSUE TITLE
possible to show tasks and chores in the same list?

### ISSUE THREAD

**Issue by cranky-coder** [isabellaalstrom/lovelace-grocy-chores-card#63]
I have the card installed.  

Here is my simple config for one kid in my house.
```
cards:
          - type: custom:grocy-chores-card
            entity:
              - sensor.grocy_chores
              - sensor.grocy_tasks
            title: Will Chores
            show_quantity: 5
            show_days: 2
            filter_user: 2
            show_track_button: true
```

However it only shows chores.  If i remove filter user, the task now shows up as well as the chores.  The chores and the tasks are both assigned to the same userid.  

Is it possible to have both show up in the same list?  This would make 1 off chores and recurring chores mix well on the chore lists for the kids. 

Thank you!
