### ISSUE TITLE
filter_user stopped working

### ISSUE THREAD

**Issue by Gibby** [isabellaalstrom/lovelace-grocy-chores-card#68]
Example from `sensor.grocy_chores`

```
- id: 5
  name: Foo - Take out garbage
  description: ''
  period_type: daily
  period_config: ''
  period_days: 0
  track_date_only: false
  rollover: false
  assignment_type: in-alphabetical-order
  assignment_config: '4'
  next_execution_assigned_to_user_id: 4
  userfields: null
  last_tracked_time: '2022-02-04T12:50:34'
  next_estimated_execution_time: '2022-02-05T12:50:34'
  last_done_by:
    id: 2
    username: bar
    first_name: Bar
    last_name: ''
    display_name: Bar
  track_count: 0
  next_execution_assigned_user:
    id: 4
    username: foo
    first_name: Foo
    last_name: ''
    display_name: Landen
   ```
   
   Card
   ```
    - type: custom:grocy-chores-card
      entity: sensor.grocy_chores
      title: "Foo's Chores"
      user_id: 4
      filter_user: 4
      custom_translation:
        Track: "Complete Now"
  ```
  
  
  Result, no card shows up.
  If I removed the `filter_user` it works fine.
  
  `filter:` is working fine though.
