### ISSUE TITLE
grocy_tasks entity doesn't pull tasks if any of the tasks are "uncategorized" in Grocy

### ISSUE THREAD

**Issue by birdwing** [isabellaalstrom/lovelace-grocy-chores-card#71]
So I was confused as to why the grocy_tasks entity didn't have any tasks in it.
After some testing I found that if any Task in grocy is "uncategorized" then the tasks fail to get pulled.
I checked the Grocy API to make sure it wasn't an issue there, the API sends the tasks with a _empty_ category id.
![null_cat_id](https://user-images.githubusercontent.com/6484397/172894475-ecf8b105-17e3-4d81-aabd-62211c6d2ed6.png)

I believe that the integration is expecting this to be an integer, so an empty string throws an error.

Here are some screenshots:
If any task in Grocy is _uncategorized_
![uncat_task](https://user-images.githubusercontent.com/6484397/172893665-0b75f484-7a46-44a1-84f1-ef395eefc863.png)
Then todo list is empty:
![no_tasks](https://user-images.githubusercontent.com/6484397/172893714-3c4202cb-60b2-46f3-a167-cd9545560ac5.png)
and the entity state is "unknown"
![state_unknown](https://user-images.githubusercontent.com/6484397/172893941-c4bbd01b-da6a-406b-aa58-b1f15c756767.png)

If all  tasks have a category
![cat_tasks](https://user-images.githubusercontent.com/6484397/172894000-f5037acb-d17b-4203-8bf0-f06cb25a3c8a.png)
Then todo list shows the tasks:
![tasks](https://user-images.githubusercontent.com/6484397/172894052-f490ea46-0f16-4a89-903e-3b581b6cf677.png)
and the entity state shows number of tasks and tasks are loaded
![state_correct](https://user-images.githubusercontent.com/6484397/172894255-b2b3931b-f8ca-4ee8-a7a5-fdfd097f8064.png)

Just to rule out any templating issues, here is the YAML for the card:
```yml
type: custom:grocy-chores-card
entity: sensor.grocy_tasks
title: Todo List
show_quantity: null
show_days: null
show_assigned: false
show_last_tracked: true
show_last_tracked_by: false
show_track_button: true
show_create_task: true
browser_mod: false
```
